version: '1.0'
services:
  jenkins:
    build: .
    user: root
    container_name: jenkins
    environment:
      - TZ=Asia/Seoul
    ports:
      - "8080:8000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  jenkins_home: